// Shared mutable state — wired to live main.js variables after initialization.
// Extracted modules (layout, peel-segments, effects, events, physics) import this
// to read current game state without circular dependencies.
// main.js keeps bare variable names; state is synced after every reassignment there.
//
// Keep the object global so cache-busted and non-cache-busted module URLs still
// resolve to the same live singleton in the browser module graph.
const defaultState = {
  // Arrays/maps wired by reference (mutated in-place — always live)
  letters: null,
  blockRanges: null,
  segmentRanges: null,
  textBlocks: null,
  blockInDom: null,
  looseParts: null,
  peelStrokes: null,
  particles: null,
  physicsProps: null,
  firedTriggerKeys: null,
  shapeOrigins: null,
  drawPathOrigins: null,
  drags: null,
  cursorForcePointers: null,
  // Scalars synced after every reassignment in main.js
  pieceConfig: null,
  activeBlocks: null,
  selectedBlockIdx: 0,
  gravityOn: false,
  simulationPaused: false,
  unraveling: false,
  activeBehaviors: null,
  BLOCK_GAP: 0,
  FORCE_FIELDS: null,
  frameViewport: null,
  currentPalette: null,
  currentGradientPresets: null,
  currentGradientStops: null,
  // Runtime constants (computed once at startup, never reassigned)
  LINE_HEIGHT: 0,
  MARGIN: 0,
  TOP_MARGIN: 0,
  BOTTOM_MARGIN: 0,
  baseFontSize: '',
  baseFontPx: 0,
  FONT: '',
  isTouchMobile: false,
  container: null,
  // Session 6 — peel-segments.js
  spanishHyphenator: null,
  CONSTRAINT_DIST: 0,
  UNLOCK_THRESHOLD: 0,
  INITIAL_UNLOCK_COUNT: 0,
  EFFECTIVE_ITERATIONS: 0,
  TICK_GRAVITY: 0,
  positions: null,
  restLengths: null,
  crossBlockConstraints: null,
  ties: null,
  tangledLines: null,
  tieNodeDrags: null,
  tangledLineDrags: null,
  reflowPositions: null,
  reflowStarted: null,
  anchorPeelNeighbors: null,
  initializedCrossBlockArcs: null,
  releasedCrossBlockArcs: null,
  // Session 7 — effects.js
  particleEmitters: null,
  MAX_PARTICLES: 0,
  MAX_PARTICLES_PER_STEP: 0,
  particlesSpawnedThisStep: 0,
  STEP_MS: 0,
  SIM_STEP_SCALE: 0,
  physicsPropDrags: null,
  effectsCtx: null,
  completedBlockTimes: null,
  activeBlockFlags: null,
  lineartAuthoring: null,
  drawTextAuthoring: null,
  // Function refs set from main.js (hoisted function declarations)
  isBlockVisible: null,
  getStepAdvanceDelayMs: null,
  getLineartAuthoringLayout: null,
  drawPathPointToScreen: null,
  renderLooseParts: null,
  armAudio: null,
  getSelectedDrawPath: null,
  // Session 8a — events.js
  currentForceFields: null,
  hiddenBlocks: null,
  namedFlags: null,
  completedBlocks: null,
  lastBehaviorVisibilityKey: '',
  runBgColorAction: null,
  getLetterCenter: null,
  getBlockVisibleCenter: null,
  // Session 8b — physics.js
  TICK_DAMPING: 0,
  LONG_STRIP_MIN_LETTERS: 0,
  LONG_STRIP_SENSITIVITY: 0,
  LONG_STRIP_VELOCITY_REF: 0,
  MIGRATION_TARGET_DEPTH: 0,
  MIGRATION_VELOCITY_MIN: 0,
  MIGRATION_VELOCITY_MAX: 0,
  MIGRATION_STEPS_MAX: 0,
  mobileRuntime: false,
  SIM_HZ: 0,
  gapLinkDecayTargets: null,
  blockStartedFlags: null,
  startedPeelSegments: null,
  pileStampedSegs: null,
  pileHeights: null,
  PILE_GROW_SEC: 0,
  MAX_PILE_H: 0,
  unlockClock: 0,
  unravelIdx: -1,
  frameLetterRange: null,
  hint: null,
  sceneScrollRestoreTarget: 0,
  censorRevealEls: null,
  censorRevealedFlags: null,
  els: null,
  lastRenderedX: null,
  lastRenderedY: null,
  lastRenderedAngle: null,
  // Function refs for physics.js (hoisted function declarations)
  isDragged: null,
  isLetterFrozen: null,
  getPileFloor: null,
  isUnravelDone: null,
  unlockLetter: null,
  advanceUnravelQueue: null,
  updateForceFieldVisualOffsets: null,
  getLetterConstraintCenter: null,
  getLetterCollisionRadius: null,
  isCollidableLetter: null,
  wakeStarterIdleSegment: null,
  getLetterRenderOffsetY: null,
  markDragStateDirty: null,
  forEachFrameLetter: null,
  forEachFrameConstraint: null,
  deleteDynamicOverflow: null,
  simulateLooseParts: null,
  simulatePeelStrokes: null,
  getRenderedY: null,
  updateFrameState: null,
  continueSceneScrollRestore: null,
  positionAttachments: null,
  syncPeelStrokeOrigins: null,
  positionInlineLinkButtons: null,
  positionTimedButtons: null,
  positionClipShapeFrames: null,
  positionHint: null,
  positionBlockGizmos: null,
  getLetterVisualOffset: null,
  getBlockRenderOffsetY: null,
  updateBehaviorVisibility: null,
  updateDebugStats: null,
};

export const state = globalThis.__tiritaState || (globalThis.__tiritaState = defaultState);
